// Blocks Beyond the Stars — Copyright (c) 2026 Justus Dütscher & Marcel Dütscher (JuMaVe Games)
// SPDX-License-Identifier: AGPL-3.0-or-later
// This file is part of Blocks Beyond the Stars. See LICENSE for the full AGPL-3.0 text.
using System.Diagnostics;

namespace BlocksBeyondTheStars.WorldHost;

/// <summary>
/// Starts/stops one dedicated-server container per world. Abstracted so the orchestrator's allocation
/// logic is testable without Docker; production uses <see cref="DockerCliLauncher"/>.
/// </summary>
public interface IInstanceLauncher
{
    /// <summary>Starts the instance for a world and returns the container id (throws on failure).</summary>
    string Start(WorldRecord world);

    /// <summary>Stops the container (triggering the server's clean drain+save via SIGTERM). Idempotent.</summary>
    void Stop(string containerId);

    /// <summary>Whether the container is still running — false once an idle shutdown has exited it.</summary>
    bool IsRunning(string containerId);

    /// <summary>CPU/memory snapshot of every container on the host (admin server-health card). Empty
    /// when docker is unavailable — the card degrades, nothing fails. NOTE: <c>docker stats</c> samples
    /// for ~1-2 s, so callers must keep this off the page-render path.</summary>
    IReadOnlyList<ContainerStat> ContainerStats();
}

/// <summary>
/// Docker-CLI launcher: shells out to <c>docker</c> with <see cref="ProcessStartInfo.ArgumentList"/>
/// (argv-level, no shell interpolation), so no value can smuggle extra arguments in. Defense in depth on
/// top of that: everything user-influenced that reaches this class is already validated/generated by the
/// registry (world ids are server-generated hex; the display name is passed only as an ENV VALUE).
///
/// Container shape per world:
///  - name <c>bbs-world-&lt;id&gt;</c>, volume <c>bbs-world-&lt;id&gt;-saves</c> mounted at /app/saves
///  - <c>--restart=no</c> — REQUIRED: the instance exits itself on idle (BBS_IDLE_SHUTDOWN_MINUTES);
///    an auto-restart policy would wake it right back up and defeat sleeping
///  - one stable host port published as udp (native gameplay) AND tcp (WS gateway; /status health probe)
///  - caddy-docker-proxy labels so <c>w-&lt;id&gt;.&lt;BaseDomain&gt;</c> routes wss onto the gateway
/// </summary>
public sealed class DockerCliLauncher : IInstanceLauncher
{
    private readonly WorldHostConfig _config;

    public DockerCliLauncher(WorldHostConfig config) => _config = config;

    public string Start(WorldRecord world)
    {
        // Bind mount (not a named volume) so WorldHost itself can implement save upload/export by touching
        // the world.db directly while the instance is stopped.
        string savesDir = SavePaths.HostSavesDir(_config, world.Id);
        Directory.CreateDirectory(savesDir);

        // Instances exit on idle but their container OBJECT remains (we run without --rm so logs stay
        // inspectable while a world sleeps) — remove any stale one first or the re-wake's `docker run
        // --name bbs-world-<id>` fails with a name conflict. Best effort: "no such container" is fine.
        Run(new List<string> { "rm", "-f", $"bbs-world-{world.Id}" });

        var (exitCode, stdout, stderr) = Run(BuildRunArgs(_config, world, savesDir));
        if (exitCode != 0)
        {
            throw new InvalidOperationException($"docker run failed for world {world.Id}: {stderr.Trim()}");
        }

        return stdout.Trim(); // container id
    }

    /// <summary>Assembles the full <c>docker run</c> argv for one world instance. Static + pure (and
    /// public) so the container shape (limits, env passthrough, labels) is unit-testable without Docker.</summary>
    public static List<string> BuildRunArgs(WorldHostConfig config, WorldRecord world, string savesDir)
    {
        var args = new List<string>
        {
            "run", "-d",
            "--name", $"bbs-world-{world.Id}",
            "--restart=no",
            "--stop-timeout", "180", // match the compose stop_grace_period: drain + save needs time — a stop during initial worldgen (#243) must outlast generation on the CPU fence
            "--network", config.DockerNetwork,
            "-p", $"{world.HostPort}:31415/udp",
            "-p", $"127.0.0.1:{world.HostPort}:31415/tcp", // tcp side only for the local /status probe; public wss goes through Caddy
            "-v", $"{savesDir}:/app/saves",
            "-e", $"BBS_WORLD={world.Id}",
            "-e", $"BBS_SERVER_NAME={world.DisplayName}",
            // glitch.fun arcade worlds get their own (smaller) player cap; applied on container start.
            "-e", $"BBS_MAX_PLAYERS={(world.Channel == WorldChannel.Glitch ? config.GlitchMaxPlayers : config.MaxPlayersPerWorld)}",
            // Kept-awake arcade worlds never self-exit (0 = idle shutdown off) — a store visitor
            // should land in a running world, not wait out a cold worldgen.
            "-e", $"BBS_IDLE_SHUTDOWN_MINUTES={(world.Channel == WorldChannel.Glitch && config.GlitchKeepAwake ? 0 : config.IdleShutdownMinutes)}",
            "-e", $"BBS_JOIN_TOKEN_SECRET={world.JoinSecret}",
            "-e", $"BBS_WORLD_OWNER={world.OwnerAccountId}",
            "-e", "BBS_ENABLE_WEBSOCKET=true",
            "-e", "BBS_WEBSOCKET_BIND=+",
        };

        // Resource fences: a hard memory cap (same value as --memory-swap, so a capped world can't push
        // the host into swap thrash; .NET's cgroup-aware GC applies pressure before the OOM kill), a CPU
        // ceiling and a pids cap. An OOM-killed world is just a stopped world — the next join re-wakes it.
        if (!string.IsNullOrEmpty(config.InstanceMemory))
        {
            args.AddRange(new[] { "--memory", config.InstanceMemory, "--memory-swap", config.InstanceMemory });
        }

        if (!string.IsNullOrEmpty(config.InstanceCpus))
        {
            args.AddRange(new[] { "--cpus", config.InstanceCpus });
        }

        args.AddRange(new[] { "--pids-limit", "256" });

        // Maintenance announcements (#249): the shared secret the control plane presents on the instance's
        // POST /announce. Without it neither side enables the endpoint.
        if (!string.IsNullOrEmpty(config.AnnounceToken))
        {
            args.AddRange(new[] { "-e", $"BBS_ANNOUNCE_TOKEN={config.AnnounceToken}" });
        }

        // Optional fleet AI: the instance reaches the internal-only ai container by name on the shared
        // network. Level TextOnly = NPC lines + board flavour, no auto-published AI missions.
        if (!string.IsNullOrEmpty(config.AiBackendUrl))
        {
            args.AddRange(new[]
            {
                "-e", $"BBS_AI_BACKEND_URL={config.AiBackendUrl}",
                "-e", $"BBS_AI_LEVEL={config.AiLevel}",
            });
        }

        args.AddRange(new[]
        {
            "-l", $"caddy=w-{world.Id}.{config.BaseDomain}",
            "-l", "caddy.reverse_proxy={{upstreams 31415}}",
            config.ServerImage,
        });

        return args;
    }

    public void Stop(string containerId)
    {
        if (string.IsNullOrEmpty(containerId))
        {
            return;
        }

        Run(new List<string> { "stop", containerId }); // best effort; "no such container" is fine
    }

    public bool IsRunning(string containerId)
    {
        if (string.IsNullOrEmpty(containerId))
        {
            return false;
        }

        var (exitCode, stdout, _) = Run(new List<string> { "inspect", "--format", "{{.State.Running}}", containerId });
        return exitCode == 0 && stdout.Trim() == "true";
    }

    public IReadOnlyList<ContainerStat> ContainerStats()
    {
        var (exitCode, stdout, _) = Run(new List<string> { "stats", "--no-stream", "--format", "{{json .}}" });
        return exitCode == 0 ? HostStats.ParseDockerStats(stdout) : Array.Empty<ContainerStat>();
    }

    private static (int ExitCode, string Stdout, string Stderr) Run(List<string> args)
    {
        var psi = new ProcessStartInfo("docker")
        {
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
        };
        foreach (var a in args)
        {
            psi.ArgumentList.Add(a);
        }

        using var proc = Process.Start(psi) ?? throw new InvalidOperationException("Failed to start docker CLI.");
        string stdout = proc.StandardOutput.ReadToEnd();
        string stderr = proc.StandardError.ReadToEnd();
        proc.WaitForExit(120_000);
        return (proc.HasExited ? proc.ExitCode : -1, stdout, stderr);
    }
}
