"""BlocksBeyondTheStars optional AI backend.

A separate, optional Python service (technical requirements / anf_mission_editor.md §3). It serves
LLM-authored flavour and content, and the authoritative C#/.NET server stays in charge of all of it:

  * ``POST /mission-plan`` — a structured MissionPlan. **LLM-authored when a model is configured
    (L0)**, else the deterministic template stand-in; the server validates, clamps and publishes.
  * ``POST /npc-line`` — a short, in-character line (item 15 L1/L2 + VEGA ship-AI banter),
    generated by an LLM via LangChain/LangGraph when one is configured, else a deterministic
    bilingual template (empty for the ship AI, whose scripted lines cover the offline case).
  * ``POST /mission-text`` — flavour Title/Description for a FIXED board mission (L3); the
    objective/reward stay server-coined. Returns empty fields when no LLM is available so the
    server keeps its localized static board text.

The mission JSON uses PascalCase keys/enum values to match the C# models exactly.

Run (with uv):
    uv run uvicorn app.main:app --host 127.0.0.1 --port 8077
"""
from __future__ import annotations

from fastapi import FastAPI
from pydantic import BaseModel, ConfigDict, Field

from .llm import (
    generate_mission_plan,
    generate_mission_text,
    generate_npc_line,
    llm_enabled,
)

app = FastAPI(title="BlocksBeyondTheStars AI Backend", version="0.3.0")


class MissionRequest(BaseModel):
    context: str = ""


class NpcLineRequest(BaseModel):
    """Line context (item 15 / VEGA). Field aliases are PascalCase to match the C# NpcLineRequest
    the server sends; snake_case is also accepted."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    npc_name: str = Field(default="", alias="NpcName")
    role: str = Field(default="", alias="Role")
    theme: str = Field(default="", alias="Theme")
    is_robot: bool = Field(default=False, alias="IsRobot")
    settlement: str = Field(default="", alias="Settlement")
    player_name: str = Field(default="", alias="PlayerName")
    relationship: int = Field(default=0, alias="Relationship")
    past_interactions: int = Field(default=0, alias="PastInteractions")
    language: str = Field(default="en", alias="Language")
    # L2: persona + recent interaction memory; VEGA: the current game situation.
    persona: str = Field(default="", alias="Persona")
    recent_events: str = Field(default="", alias="RecentEvents")
    situation: str = Field(default="", alias="Situation")


class MissionTextRequest(BaseModel):
    """L3: flavour-text context for one fixed board mission."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    giver_name: str = Field(default="", alias="GiverName")
    place: str = Field(default="", alias="Place")
    theme: str = Field(default="", alias="Theme")
    need_item: str = Field(default="", alias="NeedItem")
    required: int = Field(default=10, alias="Required")
    reward_item: str = Field(default="", alias="RewardItem")
    reward_count: int = Field(default=1, alias="RewardCount")
    language: str = Field(default="en", alias="Language")


# Keyword -> (objective type, target, required, reward item, reward count) — the deterministic
# stand-in used when no LLM is configured (and the guaranteed-valid floor under the LLM).
_TEMPLATES = {
    "iron": ("Mine", "iron_ore", 10, "iron_plate", 5),
    "copper": ("Mine", "copper_ore", 10, "cable", 4),
    "cable": ("Deliver", "cable", 5, "data_fragment", 1),
    "titanium": ("Mine", "titanium_ore", 8, "data_fragment", 2),
    "ice": ("Mine", "ice", 12, "data_fragment", 1),
}
_DEFAULT = ("Mine", "stone", 16, "iron_plate", 3)


def _pick(context: str):
    lowered = (context or "").lower()
    for keyword, template in _TEMPLATES.items():
        if keyword in lowered:
            return template
    return _DEFAULT


@app.get("/health")
def health() -> dict:
    return {"status": "ok", "llm": llm_enabled()}


@app.post("/npc-line")
def npc_line(req: NpcLineRequest) -> dict:
    """Returns a single line in the requested language. Never errors: falls back to a deterministic
    bilingual template (empty for role "ship_ai") when no LLM is configured or a call fails."""
    text = generate_npc_line(
        {
            "npc_name": req.npc_name,
            "role": req.role,
            "theme": req.theme,
            "is_robot": req.is_robot,
            "settlement": req.settlement,
            "player_name": req.player_name,
            "relationship": req.relationship,
            "past_interactions": req.past_interactions,
            "language": req.language,
            "persona": req.persona,
            "recent_events": req.recent_events,
            "situation": req.situation,
        }
    )
    return {"Text": text}


@app.post("/mission-text")
def mission_text(req: MissionTextRequest) -> dict:
    """L3: LLM flavour Title/Description for a fixed board mission. Empty fields when no LLM —
    the server keeps its localized static board text then."""
    text = generate_mission_text(
        {
            "giver_name": req.giver_name,
            "place": req.place,
            "theme": req.theme,
            "need_item": req.need_item,
            "required": req.required,
            "reward_item": req.reward_item,
            "reward_count": req.reward_count,
            "language": req.language,
        }
    )
    return text or {"Title": "", "Description": ""}


@app.post("/mission-plan")
def mission_plan(req: MissionRequest) -> dict:
    # L0: a real LLM authors the plan when configured; the C# server validates + clamps either way.
    plan = generate_mission_plan(req.context)
    if plan is not None:
        return plan

    # Deterministic template fallback (no LLM / call failed) — always valid against base content.
    obj_type, target, required, reward_item, reward_count = _pick(req.context)
    return {
        "Title": f"Field Order: {target.replace('_', ' ').title()}",
        "Description": (
            f"Command needs {required} {target.replace('_', ' ')}. "
            f"{req.context.strip()[:160]}".strip()
        ),
        "GiverName": "Outpost Control",
        "StartDialog": "We have a job that fits your gear. Bring back what we need.",
        "CompleteDialog": "Good work, pilot. The supplies will help everyone here.",
        "Difficulty": "normal",
        "Objectives": [
            {"Type": obj_type, "Target": target, "Required": required}
        ],
        "SuggestedRewards": [
            {"Item": reward_item, "Count": reward_count}
        ],
    }
