"""Spacecraft optional AI backend.

A separate, optional Python service (technical requirements / anf_mission_editor.md §3). It serves
two things, and the authoritative C#/.NET server stays in charge of both:

  * ``POST /mission-plan`` — a structured MissionPlan the server validates, clamps and publishes.
    Still a deterministic template stand-in (the HTTP contract is the point).
  * ``POST /npc-line`` — a short, in-character NPC greeting (item 15), generated by an LLM via
    LangChain/LangGraph when one is configured, else a deterministic bilingual template. Used as
    flavour only; the server/client always have their own static fallback.

The mission JSON uses PascalCase keys/enum values to match the C# MissionPlan model exactly.

Run (with uv):
    uv run uvicorn app.main:app --host 127.0.0.1 --port 8077
"""
from __future__ import annotations

from fastapi import FastAPI
from pydantic import BaseModel, ConfigDict, Field

from .llm import generate_npc_line, llm_enabled

app = FastAPI(title="Spacecraft AI Backend", version="0.2.0")


class MissionRequest(BaseModel):
    context: str = ""


class NpcLineRequest(BaseModel):
    """Greeting context (item 15). Field aliases are PascalCase to match the C# NpcLineRequest the
    server sends; snake_case is also accepted."""

    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    npc_name: str = Field(default="", alias="NpcName")
    role: str = Field(default="", alias="Role")
    theme: str = Field(default="", alias="Theme")
    is_robot: bool = Field(default=False, alias="IsRobot")
    settlement: str = Field(default="", alias="Settlement")
    player_name: str = Field(default="", alias="PlayerName")
    relationship: int = Field(default=0, alias="Relationship")
    past_interactions: int = Field(default=0, alias="PastInteractions")
    language: str = Field(default="en", alias="Language")


# Keyword -> (objective type, target, required, reward item, reward count)
_TEMPLATES = {
    "iron": ("Mine", "iron_ore", 10, "iron_plate", 5),
    "copper": ("Mine", "copper_ore", 10, "cable", 4),
    "cable": ("Deliver", "cable", 5, "data_fragment", 1),
    "titanium": ("Mine", "titanium_ore", 8, "data_fragment", 2),
    "ice": ("Mine", "ice", 12, "data_fragment", 1),
}
_DEFAULT = ("Mine", "stone", 16, "iron_plate", 3)


def _pick(context: str):
    lowered = (context or "").lower()
    for keyword, template in _TEMPLATES.items():
        if keyword in lowered:
            return template
    return _DEFAULT


@app.get("/health")
def health() -> dict:
    return {"status": "ok", "llm": llm_enabled()}


@app.post("/npc-line")
def npc_line(req: NpcLineRequest) -> dict:
    """Returns a single greeting line in the requested language. Never errors: falls back to a
    deterministic bilingual template when no LLM is configured or a call fails."""
    text = generate_npc_line(
        {
            "npc_name": req.npc_name,
            "role": req.role,
            "theme": req.theme,
            "is_robot": req.is_robot,
            "settlement": req.settlement,
            "player_name": req.player_name,
            "relationship": req.relationship,
            "past_interactions": req.past_interactions,
            "language": req.language,
        }
    )
    return {"Text": text}


@app.post("/mission-plan")
def mission_plan(req: MissionRequest) -> dict:
    obj_type, target, required, reward_item, reward_count = _pick(req.context)

    # The "creative layer" would be LLM-written; here it is a simple, on-theme template.
    return {
        "Title": f"Field Order: {target.replace('_', ' ').title()}",
        "Description": (
            f"Command needs {required} {target.replace('_', ' ')}. "
            f"{req.context.strip()[:160]}".strip()
        ),
        "GiverName": "Outpost Control",
        "StartDialog": "We have a job that fits your gear. Bring back what we need.",
        "CompleteDialog": "Good work, pilot. The supplies will help everyone here.",
        "Difficulty": "normal",
        "Objectives": [
            {"Type": obj_type, "Target": target, "Required": required}
        ],
        "SuggestedRewards": [
            {"Item": reward_item, "Count": reward_count}
        ],
    }
