<#
.SYNOPSIS
  Builds and packages the Unity WebGL client for the glitch.fun arcade (upload ZIP + optional CLI deploy).

.DESCRIPTION
  The glitch.fun arcade build is the portal-relay shape: the git-ignored generated secrets partial bakes
  ONLY Enabled + PortalUrl (no Glitch title token — the client requests its arcade session and relays
  heartbeats through the WorldHost, which holds the token server-side; see BBS_WH_GLITCH_* in
  docs/developer/HOSTED_WORLDS.md).

  Steps:
    1. sync shared libs/content into the client (skippable with -SkipPrereqs)
    2. write client/Assets/.../GlitchIntegrationSecrets.Generated.cs (removed again afterwards)
    3. Unity batchmode BuildScript.BuildWebGL -> client/Build/WebGL
    4. ZIP the folder CONTENTS (index.html at the ZIP ROOT — Glitch's deploy engine rejects
       folder-in-folder ZIPs) -> artifacts/glitch/bbs-webgl-<version>.zip
    5. with -Deploy: hand the WebGL folder to the external Glitch CLI (glitch-deploy) using
       GLITCH_DEPLOY_TOKEN. Without -Deploy the ZIP is for the manual Deploy Page upload.

.PARAMETER Version
  SemVer stamped into the build (-buildVersion). Default: bundleVersion from ProjectSettings.asset.

.PARAMETER PortalUrl
  WorldHost portal origin baked into the build. Default: $env:GLITCH_PORTAL_URL, else the live fleet
  portal https://play.blocksbeyondthestars.de.

.PARAMETER UnityPath
  Path to Unity.exe. Defaults to the Unity Hub install of the project's editor version.

.PARAMETER SkipBuild
  Package/deploy an existing client/Build/WebGL folder without rebuilding.

.PARAMETER SkipPrereqs
  Skip the sync-client-libs step (e.g. right after another client build).

.PARAMETER Deploy
  After packaging, deploy via the Glitch CLI. Needs GLITCH_DEPLOY_TOKEN and the CLI on PATH as
  `glitch-deploy` (or GLITCH_DEPLOY_CLI pointing at its entry script, run through node).

.EXAMPLE
  ./scripts/publish-glitch-webgl.ps1                                   # build + ZIP for manual upload
  $env:GLITCH_DEPLOY_TOKEN = '...'; ./scripts/publish-glitch-webgl.ps1 -Deploy
#>
param(
    [string] $Version = '',
    [string] $PortalUrl = '',
    [string] $UnityPath = "C:\Program Files\Unity\Hub\Editor\6000.4.9f1\Editor\Unity.exe",
    [switch] $SkipBuild,
    [switch] $SkipPrereqs,
    [switch] $Deploy
)

$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot
$project = Join-Path $repo 'client'
$outDir = Join-Path $project 'Build/WebGL'
$secretsFile = Join-Path $project 'Assets/BlocksBeyondTheStars/Scripts/GlitchIntegrationSecrets.Generated.cs'

if ([string]::IsNullOrWhiteSpace($PortalUrl)) {
    $PortalUrl = if ($env:GLITCH_PORTAL_URL) { $env:GLITCH_PORTAL_URL } else { 'https://play.blocksbeyondthestars.de' }
}
$PortalUrl = $PortalUrl.TrimEnd('/')

if ([string]::IsNullOrWhiteSpace($Version)) {
    $projSettings = Get-Content (Join-Path $repo 'client/ProjectSettings/ProjectSettings.asset') -Raw
    if ($projSettings -match '(?m)^\s*bundleVersion:\s*(\S+)') { $Version = $Matches[1] }
    else { Write-Error 'Could not read bundleVersion from ProjectSettings.asset; pass -Version explicitly.' }
}

if (-not $SkipBuild) {
    if (-not $SkipPrereqs) {
        & (Join-Path $PSScriptRoot 'sync-client-libs.ps1')
    }

    if (-not (Test-Path $UnityPath)) {
        Write-Error "Unity editor not found at '$UnityPath'. Pass -UnityPath to your Unity 6000.4.x Unity.exe."
    }

    # Bake the arcade (relay) configuration. Deliberately NO title token: this file only points the
    # client at our portal. Always removed again — even the tokenless variant stays out of git.
    $testInstallId = if ($env:GLITCH_TEST_INSTALL_ID) { $env:GLITCH_TEST_INSTALL_ID } else { '' }
    @"
// Generated by scripts/publish-glitch-webgl.ps1 — never committed (git-ignored), removed after the build.
namespace BlocksBeyondTheStars.Build
{
    public static partial class GlitchIntegrationSecrets
    {
        static partial void ApplyEnabled(ref bool enabled) => enabled = true;
        static partial void ApplyPortalUrl(ref string value) => value = "$PortalUrl";
        static partial void ApplyDeveloperTestInstallId(ref string value) => value = "$testInstallId";
    }
}
"@ | Set-Content -Path $secretsFile -Encoding utf8NoBOM

    $log = Join-Path $project 'build-webgl.log'
    Write-Host "Building WebGL player for glitch.fun (portal $PortalUrl, v$Version — this takes a while)..." -ForegroundColor Cyan
    try {
        # Start-Process -Wait, NOT `&`: Unity.exe is a GUI-subsystem binary, so the call operator can
        # return immediately without an exit code — which once deleted the secrets partial while the
        # build was still importing the project.
        $unity = Start-Process -FilePath $UnityPath -PassThru -Wait -WindowStyle Hidden -ArgumentList @(
            '-batchmode', '-quit', '-nographics',
            '-projectPath', $project,
            '-executeMethod', 'BlocksBeyondTheStars.Client.EditorTools.BuildScript.BuildWebGL',
            '-buildOut', 'Build/WebGL',
            '-buildVersion', $Version,
            '-logFile', $log)
        $unityExit = $unity.ExitCode
    }
    finally {
        Remove-Item $secretsFile -Force -ErrorAction SilentlyContinue
        Remove-Item "$secretsFile.meta" -Force -ErrorAction SilentlyContinue
    }

    if ($unityExit -ne 0 -or -not (Select-String -Path $log -Pattern 'build: Succeeded' -Quiet)) {
        Write-Error "Unity WebGL build failed (exit $unityExit) — see $log."
    }
}

if (-not (Test-Path (Join-Path $outDir 'index.html'))) {
    Write-Error "No WebGL build at '$outDir' (index.html missing). Run without -SkipBuild first."
}

# ZIP the folder CONTENTS so index.html sits at the ZIP root (Glitch rejects folder-in-folder).
$zipDir = Join-Path $repo 'artifacts/glitch'
New-Item -ItemType Directory -Force $zipDir | Out-Null
$zip = Join-Path $zipDir "bbs-webgl-$Version.zip"
if (Test-Path $zip) { Remove-Item $zip -Force }
Write-Host "Packaging $zip ..." -ForegroundColor Cyan
Compress-Archive -Path (Join-Path $outDir '*') -DestinationPath $zip
Write-Host ("ZIP ready: {0} ({1:N0} MB)" -f $zip, ((Get-Item $zip).Length / 1MB)) -ForegroundColor Green

if (-not $Deploy) {
    Write-Host 'No -Deploy: upload the ZIP manually on the glitch.fun Deploy Page, or let the release pipeline do it (publish-glitch job).' -ForegroundColor Yellow
    exit 0
}

if ([string]::IsNullOrWhiteSpace($env:GLITCH_DEPLOY_TOKEN)) {
    Write-Error 'GLITCH_DEPLOY_TOKEN is not set (create a deploy token on the glitch.fun tokens page).'
}

# Deploy via the OFFICIAL Glitch CLI (glitch-deploy-basic: plain POSIX shell, runs under Git Bash —
# no Node/npm needed). Same pinned commit as the release pipeline's publish-glitch job.
$cliDir = Join-Path $repo 'artifacts/glitch-cli'
$cliPin = '71e6e7c6b2e159502c43cae62f9cbc4b332009d3'
if (-not (Test-Path (Join-Path $cliDir 'bin/glitch-deploy-basic'))) {
    Write-Host 'Fetching the Glitch deploy CLI (pinned) ...' -ForegroundColor Cyan
    git clone --no-checkout https://github.com/Glitch-Gaming-Platform/Glitch-Cli-Deploy.git $cliDir
}
git -C $cliDir checkout $cliPin --quiet

$bash = (Get-Command bash -ErrorAction SilentlyContinue)?.Source
if (-not $bash) { Write-Error 'bash not found (Git Bash is required for glitch-deploy-basic).' }

$titleId = if ($env:GLITCH_TITLE_ID) { $env:GLITCH_TITLE_ID } else { '80f5dc18-dc0f-45de-9a57-8599e08669ed' }
Write-Host "Deploying v$Version to glitch.fun via glitch-deploy-basic ..." -ForegroundColor Cyan
& $bash (Join-Path $cliDir 'bin/glitch-deploy-basic') deploy $zip `
    --title $titleId --token $env:GLITCH_DEPLOY_TOKEN `
    --version $Version --entry index.html --type wasm --build-type production --wait
if ($LASTEXITCODE -ne 0) { Write-Error "Glitch deploy failed (exit $LASTEXITCODE)." }
Write-Host "Deployed WebGL v$Version to glitch.fun." -ForegroundColor Green
